services:
  - type: web
    name: nextstep-nextjs
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_BASE_URL
        value: ""
      - key: NEXT_PUBLIC_BASE_PATH
        value: ""
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: nextstep
      - key: MONGODB_COLLECTION
        value: app_store
      - key: COOKIE_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGIN
        sync: false
      - key: COOKIE_CROSS_SITE
        value: "false"
      - key: COOKIE_DOMAIN
        value: ""
